# Generated by Django 2.1.5 on 2020-05-31 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_code', models.IntegerField()),
                ('movie_name', models.CharField(max_length=20)),
                ('movie_content', models.CharField(max_length=100)),
            ],
        ),
    ]
