# Generated by Django 2.1.5 on 2020-06-14 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200531_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('userid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('userpw', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('birth', models.DateTimeField()),
                ('phonenum', models.IntegerField()),
                ('useremail', models.EmailField(max_length=254)),
            ],
        ),
    ]
