# Generated by Django 2.1.5 on 2020-06-14 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='category',
            field=models.IntegerField(default=0),
        ),
    ]
